In [2]:
%matplotlib inline
import matplotlib
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.pyplot as plt

# In order to make the import of local modules
import sys
sys.path.append('..')

# local modules
from ml.linear_regression import *

In [5]:
print(linear_regression(xs=[(1,), (2,), (3,)], ys=[(1,2,3), (2,3,5), (3,4,7)]))
print(linear_regression(xs=[1, 2, 3], ys=[(1,2,3), (2,3,5), (3,4,7)]))
print(linear_regression(xs=[1, 2, 3], ys=[(1,2,3), (2,3,5), (3,4,7)]))
print(linear_regression(xs=[(1,2), (2,3), (3,4)], ys=[(1,2,3), (2,3,5), (3,4,7)]))

[[1. 1. 2.]
 [0. 1. 1.]]
[[1. 1. 2.]
 [0. 1. 1.]]
[[1. 1. 2.]
 [0. 1. 1.]]
[[-2.  0. -5.]
 [ 3.  1.  7.]
 [-3.  0. -6.]]


In [ ]:
# TODO - explain why it works
# TODO - explain why it is like (multi-task learning, it is just a way to build, completely equivalent to doing it N times)
# TODO - explain why multi-task learning works for DL: because of parameter sharing